name: Deploy to Dev

on:
  push:
    branches-ignore:
      - main

env:
    PROJECT_ID: rahul-dev-433809
    GCS_BUCKET_NAME: function-zip-rahul

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint code with flake8
        run: |
          flake8 src/  

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      
      - name: Run tests with pytest
        run: |
          pytest tests/

  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Zip the folder
      run: zip -r ./src.zip src/

    - name: Authorize GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        project_id: ${{ secrets.PROJECT_ID }}

    # Step to Configure Docker to use the gcloud command-line tool as a credential helper
    # - name: Configure Docker
    #   run: |-
    #     gcloud auth configure-docker
    
    - name: Upload to Google Cloud Storage
      run: |-
        gsutil cp ./src.zip gs://${{ env.GCS_BUCKET_NAME }}/function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authorize GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json:  ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}
    
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy my-cloud-function \
            --region=us-east1 \
            --runtime=python39 \
            --trigger-http \
            --entry-point=main_func \
            --source=gs://${{ env.GCS_BUCKET_NAME }}/function.zip \
            --memory=256MB \
