name: Deploy to Dev

on:
  push:
    branches-ignore:
      - main

env:
    PROJECT_ID: rahul-dev-433809
    GCS_BUCKET_NAME: function-zip-rahul

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint code with flake8
        run: |
          flake8 src/  

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      
      - name: Run tests with pytest
        run: |
          pytest tests/

  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Zip the folder
      run: zip -r ./src.zip source/

    - name: Authorize GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}
    
    # Step to Authenticate with GCP
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        project_id: ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}

    # Step to Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: |-
        gcloud auth configure-docker
    
    # Step to Upload the file to GCP Bucket
    - name: Upload to Google Cloud Storage
      run: |-
        gsutil cp ./src.zip gs://${function-zip-rahul}/new_file_name

  deploy:
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          credentials_json: ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ env.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy my-cloud-function \
            --runtime python38 \ 
            --trigger-http \
            --entry-point main \
            --source gs://${{ env.GCS_BUCKET_NAME }}/function.zip \ 
            --memory 256MB \
            --timeout 60s
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DEV_GCP_CREDENTIALS_JSON }}
